sudo: enabled
dist: trusty
language: node_js
node_js: "6"
os:
  - linux
  - osx
osx_image: xcode8.3

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then wget -nc https://dl.winehq.org/wine-builds/winehq.key; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-key add winehq.key; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt update; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install --install-recommends winehq-stable; fi

addons:
  brew:
    packages:
      - fakeroot
      - rpm
      - dpkg
      - wine
  apt:
    packages:
      - fakeroot
      - rpm
      - dpkg

install:
  - npm install
  - npm update

script:
  - electron-forge make --target=linux,darwin,win32