sudo: false
dist: trusty
language: node_js
node_js: "6"
os:
  - linux
  - osx
osx_image: xcode8.3

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

addons:
  brew:
    packages:
      - fakeroot
      - rpm
      - dpkg
      - wine
  apt:
    packages:
      - fakeroot
      - rpm
      - wine64
      - dpkg
      - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
      - winehq-stable

install:
  - npm install
  - npm update

script:
  - electron-forge make --target=linux,darwin,win32