sudo: false
dist: trusty
language: node_js
node_js: "6"
os:
- linux
- osx
- win32
osx_image: xcode8.3

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
    - wine
    - dpkg
    - squirrel
    - xvfb

install:
- npm install
- npm update
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &   

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 5

script:
- electron-forge make --platform=linux,darwin,win32